// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbH6KzldseOSGqLxpDngad-VqQIsdAVhk',
    appId: '1:241151676889:web:0012f4bfe8221e92c949c8',
    messagingSenderId: '241151676889',
    projectId: 'agenda-de-eventos-b72a4',
    authDomain: 'agenda-de-eventos-b72a4.firebaseapp.com',
    storageBucket: 'agenda-de-eventos-b72a4.firebasestorage.app',
    measurementId: 'G-L4JHDEZJ5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxIGTCIK1osVikjdfIjdMSDoTCydoHPyU',
    appId: '1:241151676889:android:49b4bc2f1c0b7561c949c8',
    messagingSenderId: '241151676889',
    projectId: 'agenda-de-eventos-b72a4',
    storageBucket: 'agenda-de-eventos-b72a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOM8Bkk4oGQ2AZOrCpYKsaoOR8fS0v7X4',
    appId: '1:241151676889:ios:a33d64949b06a089c949c8',
    messagingSenderId: '241151676889',
    projectId: 'agenda-de-eventos-b72a4',
    storageBucket: 'agenda-de-eventos-b72a4.firebasestorage.app',
    iosBundleId: 'com.example.agenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOM8Bkk4oGQ2AZOrCpYKsaoOR8fS0v7X4',
    appId: '1:241151676889:ios:a33d64949b06a089c949c8',
    messagingSenderId: '241151676889',
    projectId: 'agenda-de-eventos-b72a4',
    storageBucket: 'agenda-de-eventos-b72a4.firebasestorage.app',
    iosBundleId: 'com.example.agenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbH6KzldseOSGqLxpDngad-VqQIsdAVhk',
    appId: '1:241151676889:web:f5d78ce3ea66d546c949c8',
    messagingSenderId: '241151676889',
    projectId: 'agenda-de-eventos-b72a4',
    authDomain: 'agenda-de-eventos-b72a4.firebaseapp.com',
    storageBucket: 'agenda-de-eventos-b72a4.firebasestorage.app',
    measurementId: 'G-8S97PTDSJR',
  );
}
